# Generated by Django 3.2.8 on 2021-10-13 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211012_0309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='localidae',
            new_name='localidade',
        ),
    ]
